### ISSUE TITLE
Empty page (because of duplicate permission names?)

### ISSUE THREAD

**Issue by cnotin** [iann0036/azure.permissions.cloud#1]
While reporting this issue: https://github.com/iann0036/iam-dataset/issues/20, I wanted to get a look at `Microsoft.AAD/register/action` in https://azure.permissions.cloud/
This duplicate name isn't a problem in the search bar:
![image](https://user-images.githubusercontent.com/550823/211602057-9bf1972f-f4ee-4935-99af-96dfb0bb8f86.png)

But I noticed that the [page for the Microsoft.AAD provider](https://azure.permissions.cloud/iam/Microsoft.AAD) was empty:
![image](https://user-images.githubusercontent.com/550823/211602417-e09cb81f-c67d-4d60-870a-354dd9737a20.png)

I thought that perhaps it was because of this duplicate?

But perhaps not, because there's no issue with this other 3 occurences duplicate of `Microsoft.AzureSphere/catalogs/read` on https://azure.permissions.cloud/iam/Microsoft.AzureSphere
![image](https://user-images.githubusercontent.com/550823/211602590-129ba13a-ec3c-42f5-8b97-a655e36ba61f.png)

**Comment by cnotin** [comment]
Actually, it's a different reason:
```
TypeError: Cannot read properties of null (reading 'split')
```
![image](https://user-images.githubusercontent.com/550823/211604426-e25f1656-956f-4bce-a0d5-d498047886b2.png)

Because of this entry:
![image](https://user-images.githubusercontent.com/550823/211604129-192f30d0-7334-4e33-9eee-7780e3a93591.png)

**Comment by iann0036** [comment]
Hey @cnotin,

Thanks for digging into this.

I've made an adjustment to the logic that should fix this. Let me know if that's resolved for you.

**Comment by cnotin** [comment]
Much better :) Thanks Iann!
![image](https://user-images.githubusercontent.com/550823/211948924-3a91285f-2a0b-4027-932a-3c97200321d0.png)
